name: heather
description: "Heather - Your sassy weather babe"
publish_to: "none"
version: 1.2.2+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  go_router: ^14.0.0
  dio: ^5.4.0
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0
  geolocator: ^13.0.0
  geocoding: ^3.0.0
  google_fonts: ^6.2.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  weather_icons: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_svg: ^2.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  flutter_local_notifications: ^18.0.0
  timezone: ^0.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_timezone: ^5.0.1
  flutter_dotenv: ^6.0.0
  home_widget: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
